#!/bin/bash

cd solvers/passiveGDHFoam
	wclean
cd ../passiveLaunderSFTFoam
	wclean
cd ../passiveFoxASMFoam
	wclean
cd ../passiveLaminarFoam
	wclean
cd ../passiveTransGDHFoam
	wclean
cd ../passiveTransLaminarFoam
	wclean
cd ../expEulerGDHFoam
	wclean
cd ../expEulerFoam
	wclean
cd ../RK4ScalarFoam
	wclean
cd ../RK4GDHFoam
	wclean
