#!/bin/bash

cd solvers/passiveGDHFoam
	wmake
cd ../passiveLaunderSFTFoam
	wmake
cd ../passiveFoxASMFoam
	wmake
cd ../passiveLaminarFoam
	wmake
cd ../passiveTransGDHFoam
	wmake
cd ../passiveTransLaminarFoam
	wmake
