#!/bin/bash
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ $1 == '-parallel' ]
then
#echo $1
	printf "running in parallel \n"
	runApplication blockMesh
	runApplication decomposePar
	runParallel simpleTracerFoam 2
	runApplication reconstructPar

else
	printf "running in serial \n"
	runApplication blockMesh
	runApplication simpleTracerFoam
fi
